@startuml Domain Model

allow_mixing
left to right direction

!include ./config.puml

class Order {
    * id: str
}

class OrderLine << valueobject >> {
    * orderid: str
    * sku: str
    * qty: int
}

class Batch {
    * reference: str
    sku: str
    eta: date
    --
    _purchased_quantity: int
    _allocations: [OrderLine]
}

actor Customer
actor "Purchasing\nDept. User"

Customer --> Order : places
Order::id o--> OrderLine::orderid : "comprises\nmultiple"
Batch::_allocations o--> OrderLine
"Purchasing\nDept. User" --> Batch : "purchases"

@enduml