version: "3"
services:
  app:
    image: cloudeyes/micropy-lab:3.9
    container_name: microlab
    depends_on:
      - postgres
    environment:
      - DB_HOST=localhost
      - DB_PASSWORD=p@ssw0rd
    volumes:
      - ~/notebooks:/users/smprc/notebooks
    ports:
      - "5005:80"
      - "12222:22"
      - "18888:8888"

  postgres:
    image: postgres:9.6-alpine
    container_name: pgsql-test
    environment:
      - POSTGRES_USER=smprc
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
